import Vue from 'vue';
import {
  Card,
  Form,
  FormItem,
  Input,
  Button,
  Row,
  Col,
  Link,
  Message,
  Container,
  Aside,
  Main,
  Header,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Avatar,
  Menu,
  MenuItem,
  MenuItemGroup,
  Submenu,
  Badge,
  Breadcrumb,
  BreadcrumbItem,
  TabPane,
  Tabs,
  Select,
  Option,
  Table,
  TableColumn,
  Tag,
  Switch,
  Tooltip,
  Pagination,
  Dialog,
  Radio,
  MessageBox
} from 'element-ui';

Vue.use(Card);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(Button);
Vue.use(Row);
Vue.use(Col);
Vue.use(Link);
Vue.use(Container);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Header);
Vue.use(Dropdown);
Vue.use(DropdownItem);
Vue.use(DropdownMenu);
Vue.use(Avatar);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(MenuItemGroup);
Vue.use(Submenu);
Vue.use(Badge);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(TabPane);
Vue.use(Tabs);
Vue.use(Select);
Vue.use(Option);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Tag);
Vue.use(Switch);
Vue.use(Tooltip);
Vue.use(Pagination);
Vue.use(Dialog);
Vue.use(Radio);

Vue.prototype.$message = Message;
Vue.prototype.$confirm = MessageBox.confirm;
